skip_commits:
  files:
    - '*.md'
    - '.github/**/*'
image: Visual Studio 2019
clone_depth: 1
configuration: Release
before_build:
  - |-
    mkdir build
    cd build
    cmake ..
    cd %APPVEYOR_BUILD_FOLDER%
build:
  project: build\extract-xiso.sln
  parallel: true
after_build:
  - 7z a %CONFIGURATION%.zip build\%CONFIGURATION%\extract-xiso.exe LICENSE.TXT
test: off
artifacts:
  - path: $(CONFIGURATION).zip
